//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mywebsite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarouselResource
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string LinkText { get; set; }
        public string ImgSrc { get; set; }
        public int Ordinal { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> ResourceDate { get; set; }
        public string LinkUrl { get; set; }
    }
}
