//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mywebsite.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NavbarResource
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public bool Active { get; set; }
    }
}
